Repository Ycreak/OpensourceClassicCommentary, pull requests merged in 2023-04, with the labels that each got.

#101 issue #99 fix for dashboard fragment selector
  Angular/src/app/dashboard/dashboard.component.html
Labels: issue

#94 Movement towards modularity
  Angular/package-lock.json
  Angular/package.json
  Angular/src/app/api.service.ts
  Angular/src/app/app.component.scss
  Angular/src/app/app.module.ts
  Angular/src/app/auth/auth.service.ts
  Angular/src/app/bak/multiplayer.class.ts
  Angular/src/app/bak/multiplayer.html.old
  Angular/src/app/commentary/commentary.component.html
  Angular/src/app/commentary/commentary.component.spec.ts
  Angular/src/app/commentary/commentary.component.ts
  Angular/src/app/dashboard/dashboard.component.html
  Angular/src/app/dashboard/dashboard.component.ts
  Angular/src/app/fragments/fragments.component.html
  Angular/src/app/fragments/fragments.component.scss
  Angular/src/app/fragments/fragments.component.ts
  Angular/src/app/fragments/services/fragment-utilities.service.spec.ts
  Angular/src/app/fragments/services/fragment-utilities.service.ts
  Angular/src/app/fragments/services/playground-handler.service.spec.ts
  Angular/src/app/fragments/services/playground-handler.service.ts
  Angular/src/app/models/Column.ts
  Angular/src/app/overview/overview.component.html
  Angular/src/app/overview/overview.component.scss
  Angular/src/app/overview/overview.component.spec.ts
  Angular/src/app/overview/overview.component.ts
  Angular/src/app/playground/playground.bak
  Angular/src/app/playground/playground.component.html
  Angular/src/app/playground/playground.component.scss
  Angular/src/app/playground/playground.component.ts
  Angular/src/app/services/column-handler.service.spec.ts
  Angular/src/app/services/column-handler.service.ts
  Angular/src/environments/environment.prod.ts
  Angular/src/environments/environment.ts
  Angular/src/styles.scss
  Server/bak/move.py
  Server/config.py
  package-lock.json
Labels: must have

#103 Text blob now properly retrieved
  Angular/src/app/api.service.ts
  Angular/src/app/commentary/commentary.component.ts
  Angular/src/app/dashboard/dashboard.component.html
  Angular/src/app/dashboard/dashboard.component.ts
  Angular/src/app/dialogs/about-dialog.html
  Angular/src/app/fragments/fragments.component.html
  Angular/src/app/fragments/fragments.component.ts
  Angular/src/app/models/Column.ts
  Angular/src/app/overview/overview.component.html
  Angular/src/app/overview/overview.component.spec.ts
  Angular/src/app/overview/overview.component.ts
  Angular/src/app/playground/playground.component.html
  Angular/src/app/text/text.component.ts
  deploy_angular.sh
Labels: feature request
