Repository Ycreak/OpensourceClassicCommentary, pull requests merged in 2024-02, with the labels that each got.

#271 Linked commentaries now correctly show translation
  angular/src/app/commentary/commentary.component.html
  angular/src/app/commentary/translation/translation.component.ts
  angular/src/app/overview/overview.component.html
  angular/src/app/playground/playground.component.ts
Labels: enhancement

#272 Notes can be moved again
  angular/src/app/playground/playground.component.ts
Labels: bug

#263 add testimonium and broader context to API
  angular/src/app/api.service.ts
  flask/.gitignore
  flask/endpoints/fragment.py
  flask/endpoints/testimonium.py
  flask/endpoints/text.py
  flask/models/fragment.py
  flask/models/testimonium.py
  flask/models/text.py
  flask/server.py
Labels: feature request

#278 Cypress + Cypress studio
  angular/cypress.config.ts
  angular/cypress/e2e/columns.cy.js
  angular/cypress/e2e/commentary.cy.js
  angular/cypress/e2e/dashboard.cy.js
  angular/cypress/e2e/overview.cy.js
  angular/cypress/fixtures/example.json
  angular/cypress/support/commands.ts
  angular/cypress/support/e2e.ts
  angular/cypress/tsconfig.json
Labels: must have

#280 Zotero fix
  angular/src/app/columns/columns.component.html
  angular/src/app/dashboard/bibliography/bibliography.component.ts
  angular/src/app/filters/document-filter/document-filter.component.html
  angular/src/app/overview/overview.component.html
Labels: enhancement
